site:
  base_url: ${WIKI_BASE_URL:-http://localhost:3000}
  # links:
  #   - en/home
  cookies:
    - key: jwt
      value: ${WIKIJS_JWT_TOKEN}
browser:
  headless: ${CHROMIUM_HEADLESS_MODE:-true}
  inject:
    css:
      - content: |
          nav.v-navigation-drawer,header.v-sheet,footer.v-footer{display: none;}
          main.v-main{padding: 0 !important;}
concurrency: 5
output:
  filename: wikijs
